name: Rust

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3,15 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # make sure nightly, beta and stable are installed
      - name: install nightly
        run: rustup install nightly
      - name: install beta
        run: rustup install beta
      - name: install stable
        run: rustup install stable
      # install master installer
      - name: install rustup-toolchain-install-master
        run: cargo install --git https://github.com/kennytm/rustup-toolchain-install-master
      - name: install master toolchain
        run: rustup-toolchain-install-master -f -n master
      # clone rustc to run icemaker in
      - name: clone rustc
        run: git clone https://github.com/rust-lang/rust rust --depth 1
      - name: clone icemaker
        run: git clone https://github.com/matthiaskrgr/icemaker icemaker
      - name: build icemaker
        run: cargo build --release
        working-directory: icemaker
      - name: run icemaker on rustc
        run: ../icemaker/target/release/icemaker -s
        working-directory: rust
      - name: check if logs are untouched
        id: repo_untouched
        run: git diff --exit-code errors.json
        working-directory: rust
        continue-on-error: true
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add errors.json || true
          git commit -m "update logs" || true
        working-directory: rust
        if: steps.repo_untouched.outputs.exit_code == 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.repo_untouched.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.ARCTICE_SECRET }}
          branch: ${{ github.ref }}
